apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: core-suite-frontend-image
    newName: ghcr.io/eed-web-application/core-suite-frontend:sha-5a3b1ac